# Generated by Django 3.2.12 on 2022-02-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0003_auto_20220202_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='game_id',
        ),
    ]
