# Generated by Django 3.2.12 on 2022-02-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0004_rename_game_game_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='removed_from_game',
            field=models.BooleanField(default=False),
        ),
    ]
