# Generated by Django 3.2.12 on 2022-02-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0005_student_removed_from_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='removed_from_game',
        ),
    ]
