# Generated by Django 3.2.12 on 2022-02-21 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0008_auto_20220221_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='finished_playing_at',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='started_playing_at',
            field=models.TimeField(),
        ),
    ]
