# Generated by Django 3.2.12 on 2022-02-22 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0009_auto_20220221_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='finished_playing_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='started_playing_at',
        ),
        migrations.AddField(
            model_name='student',
            name='finish_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='time_played',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='time_spent',
            field=models.FloatField(default=0.0),
        ),
    ]
