# Generated by Django 3.2.12 on 2022-02-22 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0011_remove_student_time_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='finish_time',
        ),
    ]
