# Generated by Django 3.2.12 on 2022-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0013_alter_student_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_cookie',
            field=models.IntegerField(default=1),
        ),
    ]
