# Generated by Django 3.2.12 on 2022-02-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0014_student_current_cookie'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='wrong_cookies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_cookie',
            field=models.IntegerField(default=0),
        ),
    ]
