# Generated by Django 3.2.12 on 2022-03-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0015_auto_20220225_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_over',
            new_name='game_started',
        ),
    ]
