# Generated by Django 3.2.12 on 2022-05-30 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0018_auto_20220530_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='errors_cookie_0',
        ),
        migrations.AddField(
            model_name='game',
            name='errors_cookie_11',
            field=models.IntegerField(default=0),
        ),
    ]
