# Generated by Django 3.2.12 on 2022-07-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameapp', '0019_auto_20220530_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='errors_cookie_12',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='errors_cookie_13',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='errors_cookie_14',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='errors_cookie_15',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='errors_cookie_16',
            field=models.IntegerField(default=0),
        ),
    ]
